### ISSUE TITLE
[Feature Request] Way of the Shooting Star Compatibility

### ISSUE THREAD

**Issue by InfinityArts9o** [pheonix99/ToggleableThrowingWeapons#2]
Any chance we could get CHA to ATK and DMG when using starknives with the Way of the Shooting Star feat?  That one's from Morvarch's lovely minimod:

https://github.com/MorvarchPrincess/MorvarchsPlaystyleExpansions/releases/tag/v1.0.1

**Comment by pheonix99** [comment]
It doesn't work?

Huh super weird.

I'll look into that.

**Comment by ifarmpandas** [comment]
Looks like it's broken again in https://github.com/MorvarchPrincess/MorvarchsPlaystyleExpansions/releases/tag/v1.1.0 since they switched from using `AttackStatReplacement` to `AttackStatReplacementFixed`.
